language: cpp
compiler: $CXX
os: linux

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-4.9
  - export CXX="g++-4.9"
  - sudo apt-get install -y libwxbase3.0-0 libwxbase3.0-dev libwxgtk3.0-0 libwxgtk3.0-dev wx3.0-headers wx-common libcrypto++9 libcrypto++-dev
script:
  - make
after_script:
  - make clean
