language: cpp
compiler: gcc
os: linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libwxbase3.0-0 libwxbase3.0-dev libwxgtk3.0-0 libwxgtk3.0-dev wx3.0-headers wx-common libcrypto++9 libcrypto++-dev
script:
  - make
after_script:
  - make clean
